[package]
name = "regex-railroad"
version = "0.0.3"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
neovim-lib = "0.6.1"
rmpv = "1.3.0"
rsnvim = "0.1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
