on:
  push:
    tags:
    - "v*.*.*"

name: Upload Release

jobs:
  upload-release:
    permissions: write-all
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Build
          run: cargo build --release --verbose
        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            files: |
              target/release/regex-railroad
              lua/*/**
              plugin/regex-railroad.lua
              LICENSE
              README.md

