name: Rust

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Lint
          run: cargo clippy -- -D warnings

    build-linux:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Build
          run: cargo build --release --verbose
        - name: Run tests
          run: cargo test --verbose

    build-macos:
        runs-on: macos-latest

        steps:
        - uses: actions/checkout@v4
        - name: Build
          run: cargo build --release --verbose
        - name: Run tests
          run: cargo test --verbose

    build-windows:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v4
        - name: Build
          run: cargo build --release --verbose
        - name: Run tests
          run: cargo test --verbose

